version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: global_db
      POSTGRES_USER: crm-super-admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
