services:
  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak
    restart: always
    ports:
      - "8890:8080"

    environment:
      KEYCLOAK_DATABASE_HOST: <<DB_HOST>>
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_DATABASE_USER: <<DB_USER>>
      KEYCLOAK_DATABASE_PASSWORD: <<DB_PASSWORD>>

      KEYCLOAK_ADMIN: <<ADMIN>>
      KEYCLOAK_ADMIN_PASSWORD: <<ADMIN_PASSWORD>>

      KEYCLOAK_FRONTEND_URL: https://keycloak-admin.efcon.ro:8890
      KEYCLOAK_JDBC_PARAMS: "sslmode=verify-ca&sslrootcert=/opt/bitnami/keycloak/certs/rds-ca-cert.pem"