spring:
  application:
    name: crm-service
  datasource:
    crm:
      url: jdbc:postgresql://localhost:5432/global_db
      username: ${username}
      password: ${password}
      driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 100000
      max-lifetime: 1800000

  jpa:
    hibernate:
        ddl-auto: update
    show-sql: false
    properties:
        hibernate:
          generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        jdbc:
            lob:
            non_contextual_creation: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8890/realms/crm
          jwk-set-uri: http://localhost:8890/realms/crm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ${client-id}
            client-secret: ${secret}
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8890/realms/crm
            user-name-attribute: preferred_username
keycloak:
  client:
    server-url: http://localhost:8890
    realm: crm
    client-id: ${admin-client-id}
    secret: ${admin-secret}


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: swagger-ui.html

logging:
  level:
    org.hibernate.stat: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
