spring:
  application:
    name: crm-service
  datasource:
    global:
      url: jdbc:postgresql://localhost:5432/global_db
      username: crm-super-admin
      password: 123456
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: false
    properties:
        hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        jdbc:
            lob:
            non_contextual_creation: true

