spring:
  application:
    name: crm-service
  datasource:
    crm:
      url: jdbc:postgresql://crm-database.ch6yisuca6nm.us-east-1.rds.amazonaws.com:5432/global_db
      username: crm_admin
      password: dde1OIFhx2F^B4uy
      driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 100000
      max-lifetime: 1800000

  jpa:
    hibernate:
        ddl-auto: update
    show-sql: false
    properties:
        hibernate:
          generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        jdbc:
            lob:
            non_contextual_creation: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://backend-crm.efcon.ro/auth/realms/crm
          jwk-set-uri: https://backend-crm.efcon.ro/auth/realms/crm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: crm_client
            client-secret: Br6EK5BFIcPFKODVq8CdlPRNsflhG9wG
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: https://backend-crm.efcon.ro/auth/realms/crm
            user-name-attribute: preferred_username
keycloak:
  client:
    server-url: https://backend-crm.efcon.ro/auth
    realm: crm
    client-id:  admin-cli
    secret: wN2yBMxlRNBITmHuZxdrQiLrye2T3j0K

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: swagger-ui.html

